learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('learning_logs.urls', 'learning_log'), namespace='learning_logs')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs.
"""

from django.urls import path
from . import views

urlpatterns = [
    #Home page
    path('', views.index, name='index'),

    #Topic page : show all topics
    path('topics/', views.topics, name='topics'),

    #Detail page for a single topic
    path('topics/<topic_id>/', views.topic, name='topic'),

    #Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    #Page for adding a new entry
    path('new_entry/<topic_id>', views.new_entry, name='new_entry'),

    #Page for editing an entry
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),

    #Page for a removed entry
    path('remove_entry/<entry_id>', views.remove_entry, name='remove_entry')
]

users/urls.py
"""Define URL patterns for users
    """

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    #Logout page
    path('logout/', views.logout_view, name='logout'),

    #Registration page
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about
    """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model
        """
        return self.text


class Entry(models.Model):
    """Something specific learned about a Topic
    """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model
        """
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Learning Log
    """
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics.
    """
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries.
    """
    topic = Topic.objects.get(id=topic_id)
    #Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic
    """
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic.
    """
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.topic.owner == request.user
            new_entry.save()

            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry.
    """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            next = request.GET.get('next', reverse('learning_logs:topic', args=[topic.id]))
            return HttpResponseRedirect(next)
            #return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def remove_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    entry.delete()

    context = {'topic': topic}
    return render(request, 'learning_logs/remove_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm



def logout_view(request):
    """Log the user out.
    """
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """Register a new user.
    """
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to home page.
            authenticate_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", inital-scale=1>

        <title>Learnin Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body>

        <!-- Static navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light ">
                <a class="navbar-brand active" href="{% url 'learning_logs:index' %}">Learning Log</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="navbar-text">
                                <a>Hello, {{user.username}}.</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div class="page-header">
                {% block content %}{% endblock content %}
            </div><!-- /container -->
        </div>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <div style="padding:60px">
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </div>
{% endblock header %}

{% block content %}
    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="btn btn-primary">Save changes</button>
        <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-secondary"> Cancel </a>
    </form>



{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}


{% block header %}
    <div style="padding:60px">
        <div class="jumbotron">
            <h1>Track your learning.</h1>
        </div>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list the topics you are learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry summarizing what you've learned.
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>

    </div>
{% endblock header %}


{% block content %}
    <p > <b>Add a new entry:</b> </p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Add entry</button>
        <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-secondary"> Cancel </a>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h2>Add a new topic:</h2>
    </div>
{% endblock header %}


{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
            <a href="{% url 'learning_logs:topics'%}" class="btn btn-secondary"> Cancel </a>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/remove_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </div>
{% endblock header %}

{% block content %}
    <p>The entry has been removed successfully</p>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h2>{{ topic }}</h2>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
    </div>
{% endblock header %}


{% block content %}

        {% for entry in entries %}
            <div class="card">
                <div class="card-header">
                    <h3>{{ entry.date_added|date:'d M Y H:i' }}</h3>
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a> -
                            <a href="{% url 'learning_logs:remove_entry' entry.id %}">Remove entry</a>
                        </small>
                </div>
                <div class="card-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div>

        {% empty %}
            There are no entries for this topic yet.
        {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}


{% block header %}
    <div style="padding:60px">
        <h1>Topics</h1>
        <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
    </div>
{% endblock header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <div class="card" style="width: 30rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h3>
                            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                        </h3>
                    </li>
                </ul>
            </div>

        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h2>Log in to your account.</h2>
    </div>
{% endblock header %}




{% block content %}

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Log in</button>
        <a href="{% url 'learning_logs:index' %}" class="btn btn-secondary"> Cancel </a>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_log:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <div style="padding:60px">
        <h2>Register a new account.</h2>
    </div>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Register</button>
        <a href="{% url 'learning_logs:index' %}" class="btn btn-secondary"> Cancel </a>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_log:index' %}" />
    </form>

{% endblock content %}